package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

type phaseContract struct {
	id     string
	source []byte
}

func main() {
	root, err := repositoryRoot()
	if err != nil {
		fatal(err)
	}
	if err := generate(root, filepath.Join(root, "internal", "pipeline", "contract_text.go")); err != nil {
		fatal(err)
	}
}

func repositoryRoot() (string, error) {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("locate generator source")
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(sourceFile), "..", "..", ".."))
	if _, err := os.Stat(filepath.Join(root, "skills", "canonical")); err != nil {
		return "", fmt.Errorf("locate canonical skills under %s: %w", root, err)
	}
	return root, nil
}

func generate(root, destination string) error {
	contracts, err := loadContracts(filepath.Join(root, "skills", "canonical"))
	if err != nil {
		return err
	}
	contents, err := render(contracts)
	if err != nil {
		return err
	}
	if err := os.WriteFile(destination, contents, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", destination, err)
	}
	return nil
}

func loadContracts(canonicalRoot string) ([]phaseContract, error) {
	contracts := make([]phaseContract, 0)
	seen := make(map[string]string)
	err := filepath.WalkDir(canonicalRoot, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}

		source, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		phaseID, ok, err := readPhaseID(source)
		if err != nil {
			return fmt.Errorf("read frontmatter in %s: %w", path, err)
		}
		if !ok {
			return nil
		}
		if phaseID == "" {
			return fmt.Errorf("%s declares an empty phase_id", path)
		}
		if previous, exists := seen[phaseID]; exists {
			return fmt.Errorf("phase_id %q is declared by both %s and %s", phaseID, previous, path)
		}
		seen[phaseID] = path
		contracts = append(contracts, phaseContract{id: phaseID, source: source})
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk canonical skills: %w", err)
	}
	sort.Slice(contracts, func(i, j int) bool {
		return contracts[i].id < contracts[j].id
	})
	return contracts, nil
}

func readPhaseID(source []byte) (string, bool, error) {
	frontmatter, ok, err := frontmatterBody(source)
	if err != nil {
		return "", false, err
	}
	if !ok {
		return "", false, nil
	}
	var metadata map[string]any
	if err := yaml.Unmarshal(frontmatter, &metadata); err != nil {
		return "", false, err
	}
	rawPhaseID, ok := metadata["phase_id"]
	if !ok {
		return "", false, nil
	}
	phaseID, ok := rawPhaseID.(string)
	if !ok {
		return "", true, fmt.Errorf("phase_id must be a string")
	}
	return strings.TrimSpace(phaseID), true, nil
}

func frontmatterBody(source []byte) ([]byte, bool, error) {
	start := 0
	switch {
	case bytes.HasPrefix(source, []byte("---\n")):
		start = len("---\n")
	case bytes.HasPrefix(source, []byte("---\r\n")):
		start = len("---\r\n")
	default:
		return nil, false, nil
	}

	for position := start; position < len(source); {
		lineEnd := bytes.IndexByte(source[position:], '\n')
		if lineEnd < 0 {
			line := source[position:]
			if bytes.Equal(line, []byte("---")) {
				return source[start:position], true, nil
			}
			break
		}
		lineEnd += position
		line := source[position:lineEnd]
		if bytes.HasSuffix(line, []byte("\r")) {
			line = line[:len(line)-1]
		}
		if bytes.Equal(line, []byte("---")) {
			return source[start:position], true, nil
		}
		position = lineEnd + 1
	}

	return nil, true, fmt.Errorf("unterminated YAML frontmatter")
}

func render(contracts []phaseContract) ([]byte, error) {
	var generated bytes.Buffer
	generated.WriteString("// Code generated from the source-native canonical phase skills under ../../skills/canonical; DO NOT EDIT.\n")
	generated.WriteString("//\n")
	generated.WriteString("//go:generate go run ./generate\n\n")
	generated.WriteString("package pipeline\n\n")
	generated.WriteString("var canonicalPhaseContracts = map[PhaseID]string{\n")
	for _, contract := range contracts {
		fmt.Fprintf(&generated, "\tPhaseID(%s): %s,\n", strconv.Quote(contract.id), strconv.Quote(string(contract.source)))
	}
	generated.WriteString("}\n\n")
	generated.WriteString("// PhaseContract returns the canonical executable skill text for a phase.\n")
	generated.WriteString("func PhaseContract(id PhaseID) (string, bool) {\n")
	generated.WriteString("\tcontract, ok := canonicalPhaseContracts[id]\n")
	generated.WriteString("\treturn contract, ok\n")
	generated.WriteString("}\n")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated contracts: %w", err)
	}
	return formatted, nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
